language: php

php:
  - 5.5
  - 5.6
  - hvm

env:
  - DB=mysql

services:
  - mysql

install: composer install

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS kader_test;" -uroot; fi
  - vendor/bin/doctrine-migrations migrations:migrate -n

script: php vendor/bin/phpunit